server:
  port: 8932

security:
  headers.xss: true
  sessions: if-required
  #ALWAYS
  #user.password: password
  #if-required
  #encrpyt.encoder bcrypt or SHA-256,default:SHA-256
  encrypt.encoder: SHA-256
  encrypt.hash-interations: 1024
  encrypt.strength: 8
  # ALWAYS
  #ignored: /webjars/**, /manage/css/**, /manage/dist/**, /manage/fonts/**,/manage/images/**,/manage/img/**,/manage/js/**,/validateCodeServlet, /internet/**,/memberList/**,/common/**,/user/**,/sendMessage
  defaultPassword: 123456
  oauth2:
    #resource:
      #resourceId: party-build-4a-mgmt
      #userInfoUri: http://localhost:9898/sso/user/principal
    server:
      checkTokenUri: http://10.254.23.63:8922/sso/oauth/check_token
      resourceId: party-build-4a-mgmt
      resourceSecret: ido85R&Dcenter
      tokenUrl: http://10.254.23.63:8922/sso/oauth/token?grant_type=client_credentials

spring:
  application:
    name: party-build-4a-mgmt
  primaryDataSource:
    dataSourceClassName: com.highgo.jdbc.jdbc2.optional.SimpleDataSource
    url: jdbc:highgo://10.254.23.58:5866/party_4a_mgmt?useUnicode=true&characterEncoding=utf-8
    username: highgo
    password: highgo123
    poolName: StringBootHikariCP
    maximumPoolSize: 10
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 300
  InternetDataSource:
    dataSourceClassName: com.highgo.jdbc.jdbc2.optional.SimpleDataSource
    url: jdbc:highgo://10.254.23.17:5866/sso_inter?useUnicode=true&characterEncoding=utf-8
    username: highgo
    password: chZzMikEtX1w
    poolName: StringBootHikariCP
    maximumPoolSize: 10
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 300
  BusinessDataSource:
    dataSourceClassName: com.highgo.jdbc.jdbc2.optional.SimpleDataSource
    url: jdbc:highgo://10.254.23.58:5866/sso_vpn?useUnicode=true&characterEncoding=utf-8
    username: highgo
    password: highgo123
    poolName: StringBootHikariCP
    maximumPoolSize: 10
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 300
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      show-sql: true
  redis:
    host: 10.254.23.58
    #host: localhost
    password: 1qaz@wsx?Z
    port: 6379
    database: 5
    pool:
      test-on-borrow: true
      test-while-idle: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    cache: false
    excluded-view-names: 
    check-template-location: true
    mode: LEGACYHTML5
  session: 
    store-type: redis

ribbon.eureka.enabled: true
party-simpledata-server:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
    ConnectTimeout: 3000
    ReadTimeout: 3000
    EnablePrimeConnections: true
    listOfServers: http://10.254.23.58:8962
party-education-back-server-test:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
    ConnectTimeout: 3000
    ReadTimeout: 3000
    EnablePrimeConnections: true
    listOfServers: http://10.254.23.65:7212
party-build-4a-authentication:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
    ConnectTimeout: 3000
    ReadTimeout: 3000
    EnablePrimeConnections: true
    listOfServers: http://10.254.23.63:8952

ldap:
  url: ldap://10.243.32.5:389
  login-dn: cn=Manager,dc=inspur,dc=com
  password: 123456
  base-dn: dc=inspur,dc=com
  dn.format: uid=%s,ou=%s

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.254.23.58:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  config: classpath:logback.xml
  path: ./logs

threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 300

sendMessage:
  url: http://118.190.41.112/smsJson.aspx
  userpwd: 85chuangxin1A
  message: 
  account: chuangxin
  intervaltime: 1

multipart:
  maxFileSize: 5Mb
  maxRequestSize: 30Mb

getOrganizationsUrl: http://10.254.23.58:8962/simpledata/queryOrgInfo/
queryUserInfoByHashUrl: http://10.254.23.58:8962/simpledata/queryUserInfoByHash/
checkUserExistUrl: http://10.254.23.58:8962/simpledata/checkRegularUserExistByHash
checkOrgInWhole: http://10.254.23.58:8962/trans/checkOrgInWhole/
ROLE_SECURITY: ROLE_SECURITY
ROLE_AUDITOR: ROLE_AUDITOR
downUrl: http://10.254.23.68:8888/excel/
userLogoUrl: http://10.254.23.68:8888/userLogo/
uploadLogoUrl: /data/party/userLogo/
vpnSsoUrl: //10.254.23.63:8922/sso/
sendHashurl: http://10.254.23.58:8962/simpledata/updatePersonRegisterByHash
checkUserUrl: http://10.254.23.58:8962/simpledata/checkRegularUserExistByHash
smUrl: http://10.254.23.63:8972
CLIENT_MULTI: party-big-data-center/party-education-back-ui/party-org-info-mgmt-ui/party-build-edu-back-ui/party-dues/party-build-orm/party-develop-ui/party-branch-back-ui/party-build-dtdj/party_firstsecretary_ui/party-org-transfer-ui/party-org-transfer/party-people-info-mgmt-ui/party-dt
isSendMail: 0

config:
  isneedauth: 0
order:
  getOrgOrder: http://10.254.23.66:7612/order/orderQuery
  updateOrderState: http://10.254.23.66:7612/order/orderUpdate
  updateOrderLock: http://10.254.23.66:7612/order/updateOrderLockByIds