//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 09:50:58 PM CST 
//


package com.ido85.party.sso.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fileObject" type="{http://domain.webservices.serv.nciic.com}FileObject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileObject"
})
@XmlRootElement(name = "nciicCheckFile")
public class NciicCheckFile {

    @XmlElement(required = true, nillable = true)
    protected FileObject fileObject;

    /**
     * Gets the value of the fileObject property.
     * 
     * @return
     *     possible object is
     *     {@link FileObject }
     *     
     */
    public FileObject getFileObject() {
        return fileObject;
    }

    /**
     * Sets the value of the fileObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileObject }
     *     
     */
    public void setFileObject(FileObject value) {
        this.fileObject = value;
    }

}
