//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 09:50:58 PM CST 
//


package com.ido85.party.sso.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FileObjectSetPhoneLicense_QNAME = new QName("http://domain.webservices.serv.nciic.com", "license");
    private final static QName _FileObjectSetPhoneFile_QNAME = new QName("http://domain.webservices.serv.nciic.com", "file");
    private final static QName _FileObjectSetPhoneType_QNAME = new QName("http://domain.webservices.serv.nciic.com", "type");
    private final static QName _FileObjectSetPhoneInfo_QNAME = new QName("http://domain.webservices.serv.nciic.com", "info");
    private final static QName _FileObjectErr_QNAME = new QName("http://domain.webservices.serv.nciic.com", "err");
    private final static QName _FileObjectReturnType_QNAME = new QName("http://domain.webservices.serv.nciic.com", "returnType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NciicBirthplaceCompare }
     * 
     */
    public NciicBirthplaceCompare createNciicBirthplaceCompare() {
        return new NciicBirthplaceCompare();
    }

    /**
     * Create an instance of {@link NciicKyxxEntryResponse }
     * 
     */
    public NciicKyxxEntryResponse createNciicKyxxEntryResponse() {
        return new NciicKyxxEntryResponse();
    }

    /**
     * Create an instance of {@link NciicCheckHotelResponse }
     * 
     */
    public NciicCheckHotelResponse createNciicCheckHotelResponse() {
        return new NciicCheckHotelResponse();
    }

    /**
     * Create an instance of {@link NciicGetFileResponse }
     * 
     */
    public NciicGetFileResponse createNciicGetFileResponse() {
        return new NciicGetFileResponse();
    }

    /**
     * Create an instance of {@link FileObject }
     * 
     */
    public FileObject createFileObject() {
        return new FileObject();
    }

    /**
     * Create an instance of {@link NciicCheckChina }
     * 
     */
    public NciicCheckChina createNciicCheckChina() {
        return new NciicCheckChina();
    }

    /**
     * Create an instance of {@link NciicCourtResponse }
     * 
     */
    public NciicCourtResponse createNciicCourtResponse() {
        return new NciicCourtResponse();
    }

    /**
     * Create an instance of {@link NciicAddrExactSearch }
     * 
     */
    public NciicAddrExactSearch createNciicAddrExactSearch() {
        return new NciicAddrExactSearch();
    }

    /**
     * Create an instance of {@link NciicCheckSetPhoneResponse }
     * 
     */
    public NciicCheckSetPhoneResponse createNciicCheckSetPhoneResponse() {
        return new NciicCheckSetPhoneResponse();
    }

    /**
     * Create an instance of {@link FileObjectSetPhone }
     * 
     */
    public FileObjectSetPhone createFileObjectSetPhone() {
        return new FileObjectSetPhone();
    }

    /**
     * Create an instance of {@link NciicCheckScanResponse }
     * 
     */
    public NciicCheckScanResponse createNciicCheckScanResponse() {
        return new NciicCheckScanResponse();
    }

    /**
     * Create an instance of {@link NciicExactSearch }
     * 
     */
    public NciicExactSearch createNciicExactSearch() {
        return new NciicExactSearch();
    }

    /**
     * Create an instance of {@link NciicCheckSetPhone }
     * 
     */
    public NciicCheckSetPhone createNciicCheckSetPhone() {
        return new NciicCheckSetPhone();
    }

    /**
     * Create an instance of {@link NciicFmxxEntry }
     * 
     */
    public NciicFmxxEntry createNciicFmxxEntry() {
        return new NciicFmxxEntry();
    }

    /**
     * Create an instance of {@link NciicAddrExactSearchResponse }
     * 
     */
    public NciicAddrExactSearchResponse createNciicAddrExactSearchResponse() {
        return new NciicAddrExactSearchResponse();
    }

    /**
     * Create an instance of {@link NciicCombineSearchResponse }
     * 
     */
    public NciicCombineSearchResponse createNciicCombineSearchResponse() {
        return new NciicCombineSearchResponse();
    }

    /**
     * Create an instance of {@link NciicExactSearchResponse }
     * 
     */
    public NciicExactSearchResponse createNciicExactSearchResponse() {
        return new NciicExactSearchResponse();
    }

    /**
     * Create an instance of {@link NciicDateCollectionResponse }
     * 
     */
    public NciicDateCollectionResponse createNciicDateCollectionResponse() {
        return new NciicDateCollectionResponse();
    }

    /**
     * Create an instance of {@link NciicGetCondition }
     * 
     */
    public NciicGetCondition createNciicGetCondition() {
        return new NciicGetCondition();
    }

    /**
     * Create an instance of {@link NciicCourt }
     * 
     */
    public NciicCourt createNciicCourt() {
        return new NciicCourt();
    }

    /**
     * Create an instance of {@link NciicCheckFile }
     * 
     */
    public NciicCheckFile createNciicCheckFile() {
        return new NciicCheckFile();
    }

    /**
     * Create an instance of {@link NciicCheckResponse }
     * 
     */
    public NciicCheckResponse createNciicCheckResponse() {
        return new NciicCheckResponse();
    }

    /**
     * Create an instance of {@link NciicCheckMobile }
     * 
     */
    public NciicCheckMobile createNciicCheckMobile() {
        return new NciicCheckMobile();
    }

    /**
     * Create an instance of {@link NciicKyxxEntry }
     * 
     */
    public NciicKyxxEntry createNciicKyxxEntry() {
        return new NciicKyxxEntry();
    }

    /**
     * Create an instance of {@link NciicCheckGetPhoneResponse }
     * 
     */
    public NciicCheckGetPhoneResponse createNciicCheckGetPhoneResponse() {
        return new NciicCheckGetPhoneResponse();
    }

    /**
     * Create an instance of {@link NciicCheckHotel }
     * 
     */
    public NciicCheckHotel createNciicCheckHotel() {
        return new NciicCheckHotel();
    }

    /**
     * Create an instance of {@link NciicCheck }
     * 
     */
    public NciicCheck createNciicCheck() {
        return new NciicCheck();
    }

    /**
     * Create an instance of {@link NciicCompareScanResponse }
     * 
     */
    public NciicCompareScanResponse createNciicCompareScanResponse() {
        return new NciicCompareScanResponse();
    }

    /**
     * Create an instance of {@link NciicGetFile }
     * 
     */
    public NciicGetFile createNciicGetFile() {
        return new NciicGetFile();
    }

    /**
     * Create an instance of {@link NciicCompareResponse }
     * 
     */
    public NciicCompareResponse createNciicCompareResponse() {
        return new NciicCompareResponse();
    }

    /**
     * Create an instance of {@link NciicCheckScan }
     * 
     */
    public NciicCheckScan createNciicCheckScan() {
        return new NciicCheckScan();
    }

    /**
     * Create an instance of {@link NciicCheckGetPhone }
     * 
     */
    public NciicCheckGetPhone createNciicCheckGetPhone() {
        return new NciicCheckGetPhone();
    }

    /**
     * Create an instance of {@link NciicDiscernResponse }
     * 
     */
    public NciicDiscernResponse createNciicDiscernResponse() {
        return new NciicDiscernResponse();
    }

    /**
     * Create an instance of {@link NciicFmxxEntryResponse }
     * 
     */
    public NciicFmxxEntryResponse createNciicFmxxEntryResponse() {
        return new NciicFmxxEntryResponse();
    }

    /**
     * Create an instance of {@link NciicCompareScan }
     * 
     */
    public NciicCompareScan createNciicCompareScan() {
        return new NciicCompareScan();
    }

    /**
     * Create an instance of {@link NciicDateCollection }
     * 
     */
    public NciicDateCollection createNciicDateCollection() {
        return new NciicDateCollection();
    }

    /**
     * Create an instance of {@link NciicBirthplaceCompareResponse }
     * 
     */
    public NciicBirthplaceCompareResponse createNciicBirthplaceCompareResponse() {
        return new NciicBirthplaceCompareResponse();
    }

    /**
     * Create an instance of {@link NciicCombineSearch }
     * 
     */
    public NciicCombineSearch createNciicCombineSearch() {
        return new NciicCombineSearch();
    }

    /**
     * Create an instance of {@link NciicGetConditionResponse }
     * 
     */
    public NciicGetConditionResponse createNciicGetConditionResponse() {
        return new NciicGetConditionResponse();
    }

    /**
     * Create an instance of {@link NciicCheckMobileResponse }
     * 
     */
    public NciicCheckMobileResponse createNciicCheckMobileResponse() {
        return new NciicCheckMobileResponse();
    }

    /**
     * Create an instance of {@link NciicCheckChinaResponse }
     * 
     */
    public NciicCheckChinaResponse createNciicCheckChinaResponse() {
        return new NciicCheckChinaResponse();
    }

    /**
     * Create an instance of {@link NciicCompare }
     * 
     */
    public NciicCompare createNciicCompare() {
        return new NciicCompare();
    }

    /**
     * Create an instance of {@link NciicDiscern }
     * 
     */
    public NciicDiscern createNciicDiscern() {
        return new NciicDiscern();
    }

    /**
     * Create an instance of {@link NciicCheckFileResponse }
     * 
     */
    public NciicCheckFileResponse createNciicCheckFileResponse() {
        return new NciicCheckFileResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "license", scope = FileObjectSetPhone.class)
    public JAXBElement<String> createFileObjectSetPhoneLicense(String value) {
        return new JAXBElement<String>(_FileObjectSetPhoneLicense_QNAME, String.class, FileObjectSetPhone.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "file", scope = FileObjectSetPhone.class)
    public JAXBElement<byte[]> createFileObjectSetPhoneFile(byte[] value) {
        return new JAXBElement<byte[]>(_FileObjectSetPhoneFile_QNAME, byte[].class, FileObjectSetPhone.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "type", scope = FileObjectSetPhone.class)
    public JAXBElement<String> createFileObjectSetPhoneType(String value) {
        return new JAXBElement<String>(_FileObjectSetPhoneType_QNAME, String.class, FileObjectSetPhone.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "info", scope = FileObjectSetPhone.class)
    public JAXBElement<String> createFileObjectSetPhoneInfo(String value) {
        return new JAXBElement<String>(_FileObjectSetPhoneInfo_QNAME, String.class, FileObjectSetPhone.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "err", scope = FileObject.class)
    public JAXBElement<String> createFileObjectErr(String value) {
        return new JAXBElement<String>(_FileObjectErr_QNAME, String.class, FileObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "license", scope = FileObject.class)
    public JAXBElement<String> createFileObjectLicense(String value) {
        return new JAXBElement<String>(_FileObjectSetPhoneLicense_QNAME, String.class, FileObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "file", scope = FileObject.class)
    public JAXBElement<byte[]> createFileObjectFile(byte[] value) {
        return new JAXBElement<byte[]>(_FileObjectSetPhoneFile_QNAME, byte[].class, FileObject.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "type", scope = FileObject.class)
    public JAXBElement<String> createFileObjectType(String value) {
        return new JAXBElement<String>(_FileObjectSetPhoneType_QNAME, String.class, FileObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://domain.webservices.serv.nciic.com", name = "returnType", scope = FileObject.class)
    public JAXBElement<String> createFileObjectReturnType(String value) {
        return new JAXBElement<String>(_FileObjectReturnType_QNAME, String.class, FileObject.class, value);
    }

}
