//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 09:50:58 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://api.nciic.org.cn/NciicServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ido85.party.sso.ws;
